import { Movie, Series, ContentItem } from '../types/content';
import { API_CONFIG } from '../config/api.config';

const [V0, V1, V2, V3, V4, V5] = API_CONFIG.SAMPLE_VIDEOS;

export const MOCK_MOVIES: Movie[] = [
  {
    id: 'movie-1',
    title: 'Neon Nexus: 2099',
    type: 'movie',
    year: 2026,
    rating: 8.9,
    matchScore: 99,
    duration: '2h 18m',
    maturityRating: '18+',
    quality: '4K Ultra HD',
    genres: ['Sci-Fi', 'Cyberpunk', 'Action', 'Thriller'],
    description: 'In a rain-drenched megacity controlled by sentient neural networks, an exiled cyber-detective unearths an encrypted conspiracy that could wipe out human consciousness.',
    cast: ['Elena Rostova', 'Kenji Sato', 'Marcus Vance', 'Sarah Sterling'],
    director: 'Denis Villeneuve style visionary',
    isOriginal: true,
    isFeatured: true,
    isNew: true,
    isTrending: true,
    isTopRated: true,
    status: 'published',
    posterGradient: 'from-fuchsia-700 via-indigo-950 to-black',
    backdropGradient: 'from-violet-950 via-slate-900 to-black',
    videoUrl: V3,
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-02-10T00:00:00Z',
  },
  {
    id: 'movie-2',
    title: 'The Shadow Syndicate',
    type: 'movie',
    year: 2025,
    rating: 8.7,
    matchScore: 97,
    duration: '2h 06m',
    maturityRating: '16+',
    quality: '4K Ultra HD',
    genres: ['Action', 'Thriller', 'Crime', 'Mystery'],
    description: 'When an elite covert operative is betrayed during a high-stakes Zurich heist, she must dismantle a global syndicate spanning government intelligence and criminal cartels.',
    cast: ['Sienna Cross', 'David H. Mercer', 'Julian Croft', 'Amara Patel'],
    director: 'Claire Sterling',
    isOriginal: true,
    isFeatured: true,
    isNew: true,
    isTrending: true,
    isTopRated: true,
    status: 'published',
    posterGradient: 'from-amber-600 via-stone-900 to-black',
    backdropGradient: 'from-amber-950 via-neutral-900 to-black',
    videoUrl: V2,
    createdAt: '2025-11-20T00:00:00Z',
    updatedAt: '2025-12-01T00:00:00Z',
  },
  {
    id: 'movie-3',
    title: 'Valkyrie: Ashes of Valhalla',
    type: 'movie',
    year: 2025,
    rating: 8.6,
    matchScore: 95,
    duration: '2h 24m',
    maturityRating: '18+',
    quality: '4K Ultra HD',
    genres: ['Action', 'Fantasy', 'Mythology', 'Adventure'],
    description: 'As the golden realm of the gods fractures under an ancient curse, a rogue warrior must unite nine shattered clans before eternal winter consumes Midgard.',
    cast: ['Astrid Lindholm', 'Einar Bloodaxe', 'Freja Storm', 'Lukas Grimm'],
    director: 'Gunnar Ericson',
    isOriginal: true,
    isFeatured: true,
    isNew: false,
    isTrending: true,
    isTopRated: true,
    status: 'published',
    posterGradient: 'from-emerald-600 via-teal-950 to-black',
    backdropGradient: 'from-emerald-950 via-zinc-950 to-black',
    videoUrl: V0,
    createdAt: '2025-08-10T00:00:00Z',
    updatedAt: '2025-09-01T00:00:00Z',
  },
  {
    id: 'movie-4',
    title: 'The Platinum Heist',
    type: 'movie',
    year: 2025,
    rating: 8.4,
    matchScore: 94,
    duration: '1h 58m',
    maturityRating: '16+',
    quality: '4K Ultra HD',
    genres: ['Action', 'Crime', 'Thriller'],
    description: 'A charismatic crew of international safe-crackers target an impenetrable underground vault built beneath the Monaco Grand Prix racetrack.',
    cast: ['Lucas Vance', 'Chantal Dubois', 'Mateo Cruz', 'Irina Volkova'],
    director: 'Jean-Luc Moreau',
    isOriginal: false,
    isFeatured: false,
    isNew: true,
    isTrending: true,
    isTopRated: false,
    status: 'published',
    posterGradient: 'from-amber-500 via-stone-900 to-black',
    backdropGradient: 'from-yellow-950 via-neutral-900 to-black',
    videoUrl: V4,
    createdAt: '2025-10-05T00:00:00Z',
    updatedAt: '2025-10-25T00:00:00Z',
  },
  {
    id: 'movie-5',
    title: 'Apex Velocity',
    type: 'movie',
    year: 2025,
    rating: 8.3,
    matchScore: 92,
    duration: '2h 02m',
    maturityRating: 'PG-13',
    quality: '4K Ultra HD',
    genres: ['Action', 'Sports', 'Drama'],
    description: 'A prodigy street-racer is thrust onto the premier endurance circuit to challenge an arrogant champion backed by a cutthroat multinational automotive empire.',
    cast: ['Kai Ramirez', 'Chloe Dupont', 'Axel Lindqvist', 'Garrison Holt'],
    director: 'Marco Rossi',
    isOriginal: true,
    isFeatured: false,
    isNew: true,
    isTrending: true,
    isTopRated: false,
    status: 'published',
    posterGradient: 'from-red-600 via-zinc-950 to-black',
    backdropGradient: 'from-red-950 via-neutral-900 to-black',
    videoUrl: V5,
    createdAt: '2025-09-12T00:00:00Z',
    updatedAt: '2025-09-28T00:00:00Z',
  },
  {
    id: 'movie-6',
    title: 'The Midnight Detour',
    type: 'movie',
    year: 2024,
    rating: 8.1,
    matchScore: 91,
    duration: '1h 44m',
    maturityRating: '16+',
    quality: 'HD',
    genres: ['Comedy', 'Adventure', 'Mystery'],
    description: 'Two estranged stepbrothers taking a cross-country wedding road trip accidentally pick up a briefcase containing a rogue billionaire\'s secret party itinerary.',
    cast: ['Sammy Cooper', 'Benjy Miller', 'Natasha Roman', 'Bill Higgins'],
    director: 'Adam McKay Style',
    isOriginal: false,
    isFeatured: false,
    isNew: false,
    isTrending: true,
    isTopRated: false,
    status: 'published',
    posterGradient: 'from-teal-500 via-neutral-950 to-black',
    backdropGradient: 'from-teal-950 via-neutral-900 to-black',
    videoUrl: V0,
    createdAt: '2024-06-20T00:00:00Z',
    updatedAt: '2024-07-01T00:00:00Z',
  },
  {
    id: 'movie-7',
    title: 'Eclipse Knight: Dawn of Fear',
    type: 'movie',
    year: 2026,
    rating: 8.8,
    matchScore: 97,
    duration: '2h 31m',
    maturityRating: '16+',
    quality: '4K Ultra HD',
    genres: ['Action', 'Superhero', 'Noir', 'Crime'],
    description: 'When a mysterious chemical blackout envelops Gotham-like metropolis of New Haven, a vigilante detective faces his greatest psychological nemesis.',
    cast: ['Christian Blackwood', 'Rachel Zane', 'Corbin Vance', 'Harvey Finch'],
    director: 'Matt Reeves Style',
    isOriginal: false,
    isFeatured: true,
    isNew: true,
    isTrending: true,
    isTopRated: true,
    status: 'published',
    posterGradient: 'from-blue-900 via-neutral-950 to-black',
    backdropGradient: 'from-slate-950 via-zinc-900 to-black',
    videoUrl: V3,
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-20T00:00:00Z',
  },
  {
    id: 'movie-8',
    title: 'Mind Paradox',
    type: 'movie',
    year: 2025,
    rating: 8.9,
    matchScore: 98,
    duration: '2h 15m',
    maturityRating: '18+',
    quality: '4K Ultra HD',
    genres: ['Psychological', 'Thriller', 'Mystery', 'Sci-Fi'],
    description: 'A cognitive scientist volunteering for an experimental memory rehabilitation therapy discovers her past twenty years are completely fabricated.',
    cast: ['Claire Foy', 'Ethan Hawke', 'Ken Watanabe'],
    director: 'David Fincher Style',
    isOriginal: true,
    isFeatured: false,
    isNew: false,
    isTrending: false,
    isTopRated: true,
    status: 'published',
    posterGradient: 'from-indigo-600 via-slate-950 to-black',
    backdropGradient: 'from-indigo-950 via-neutral-950 to-black',
    videoUrl: V1,
    createdAt: '2025-05-18T00:00:00Z',
    updatedAt: '2025-06-02T00:00:00Z',
  },
  {
    id: 'movie-9',
    title: 'The Last Oasis',
    type: 'movie',
    year: 2025,
    rating: 8.5,
    matchScore: 93,
    duration: '2h 11m',
    maturityRating: '16+',
    quality: '4K Ultra HD',
    genres: ['Action', 'Sci-Fi', 'Survival', 'Adventure'],
    description: 'In a scorched world devoid of water, a nomadic caravan navigates dangerous raider territory following a mythical transmission pointing to a subterranean river.',
    cast: ['Zoe Saldana', 'Pedro Pascal', 'Willem Dafoe'],
    director: 'George Miller Style',
    isOriginal: false,
    isFeatured: false,
    isNew: true,
    isTrending: true,
    isTopRated: false,
    status: 'published',
    posterGradient: 'from-orange-600 via-stone-950 to-black',
    backdropGradient: 'from-orange-950 via-stone-900 to-black',
    videoUrl: V2,
    createdAt: '2025-07-22T00:00:00Z',
    updatedAt: '2025-08-01T00:00:00Z',
  },
  {
    id: 'movie-10',
    title: 'Autumn in Vienna',
    type: 'movie',
    year: 2024,
    rating: 8.3,
    matchScore: 89,
    duration: '1h 52m',
    maturityRating: 'PG-13',
    quality: '4K Ultra HD',
    genres: ['Drama', 'Romance', 'Music'],
    description: 'A brilliant concert violinist dealing with hearing loss finds unexpected solace and new inspiration through a spontaneous collaboration with a street cellist in Vienna.',
    cast: ['Saoirse Ronan', 'Timothée Chalamet', 'Daniel Brühl'],
    director: 'Richard Linklater',
    isOriginal: false,
    isFeatured: false,
    isNew: false,
    isTrending: false,
    isTopRated: true,
    status: 'published',
    posterGradient: 'from-amber-600 via-rose-950 to-black',
    backdropGradient: 'from-amber-950 via-rose-950 to-black',
    videoUrl: V0,
    createdAt: '2024-11-14T00:00:00Z',
    updatedAt: '2024-12-05T00:00:00Z',
  },
  {
    id: 'movie-11',
    title: 'Dragon\'s Creed',
    type: 'movie',
    year: 2025,
    rating: 8.6,
    matchScore: 94,
    duration: '1h 56m',
    maturityRating: '18+',
    quality: '4K Ultra HD',
    genres: ['Action', 'Martial Arts', 'Crime'],
    description: 'A retired martial arts grandmaster living quietly in Hong Kong is dragged back into warfare when his estranged daughter is targeted by an international syndicate.',
    cast: ['Donnie Yen', 'Tony Jaa', 'Michelle Yeoh', 'Iko Uwais'],
    director: 'Yuen Woo-ping',
    isOriginal: false,
    isFeatured: false,
    isNew: true,
    isTrending: true,
    isTopRated: false,
    status: 'published',
    posterGradient: 'from-orange-600 via-neutral-950 to-black',
    backdropGradient: 'from-orange-950 via-red-950 to-black',
    videoUrl: V2,
    createdAt: '2025-08-30T00:00:00Z',
    updatedAt: '2025-09-15T00:00:00Z',
  },
  {
    id: 'movie-12',
    title: 'Temporal Fracture',
    type: 'movie',
    year: 2026,
    rating: 8.8,
    matchScore: 97,
    duration: '2h 20m',
    maturityRating: '16+',
    quality: '4K Ultra HD',
    genres: ['Sci-Fi', 'Mystery', 'Thriller'],
    description: 'A team of chronologists must repair seven minute-long ruptures in the timeline before causality collapses and the present ceases to exist.',
    cast: ['Michael B. Jordan', 'Gugu Mbatha-Raw', 'John Cho'],
    director: 'Rian Johnson',
    isOriginal: true,
    isFeatured: false,
    isNew: true,
    isTrending: false,
    isTopRated: true,
    status: 'published',
    posterGradient: 'from-fuchsia-600 via-indigo-950 to-black',
    backdropGradient: 'from-fuchsia-950 via-indigo-950 to-black',
    videoUrl: V3,
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-03-10T00:00:00Z',
  },
  {
    id: 'movie-13',
    title: 'Algorithm for Love',
    type: 'movie',
    year: 2025,
    rating: 8.1,
    matchScore: 89,
    duration: '1h 45m',
    maturityRating: 'PG-13',
    quality: 'HD',
    genres: ['Comedy', 'Romance'],
    description: 'Two rival dating app founders enter their own algorithms into a televised matchmaking contest—and are declared each other\'s one in ten million soulmate.',
    cast: ['Glen Powell', 'Sydney Sweeney', 'D\'Arcy Carden'],
    director: 'Will Gluck',
    isOriginal: false,
    isFeatured: false,
    isNew: false,
    isTrending: true,
    isTopRated: false,
    status: 'published',
    posterGradient: 'from-rose-500 via-pink-950 to-black',
    backdropGradient: 'from-pink-950 via-rose-950 to-black',
    videoUrl: V4,
    createdAt: '2025-02-14T00:00:00Z',
    updatedAt: '2025-03-01T00:00:00Z',
  },
  {
    id: 'movie-14',
    title: 'Cursed Requiem',
    type: 'movie',
    year: 2025,
    rating: 8.0,
    matchScore: 87,
    duration: '1h 54m',
    maturityRating: '18+',
    quality: '4K Ultra HD',
    genres: ['Horror', 'Supernatural', 'Thriller'],
    description: 'An archaeologist translating an ancient Sumerian musical tablet accidentally hums the forbidden frequency, unleashing a shapeshifting phantom that hunts whoever hears the melody.',
    cast: ['Rebecca Hall', 'Stellan Skarsgård', 'Barry Keoghan'],
    director: 'Fede Álvarez',
    isOriginal: true,
    isFeatured: false,
    isNew: true,
    isTrending: false,
    isTopRated: false,
    status: 'published',
    posterGradient: 'from-red-800 via-black to-black',
    backdropGradient: 'from-red-950 via-zinc-950 to-black',
    videoUrl: V2,
    createdAt: '2025-10-31T00:00:00Z',
    updatedAt: '2025-11-05T00:00:00Z',
  },
  {
    id: 'movie-15',
    title: 'Deep Canopy',
    type: 'movie',
    year: 2025,
    rating: 8.5,
    matchScore: 94,
    duration: '2h 05m',
    maturityRating: '16+',
    quality: '4K Ultra HD',
    genres: ['Adventure', 'Drama', 'Mystery'],
    description: 'Deep inside the untouched Amazonian interior, an expedition searching for a lost botanist uncovers a sentient flora network that communicates through bioluminescence.',
    cast: ['Dev Patel', 'Alicia Vikander', 'Wagner Moura'],
    director: 'Ciro Guerra',
    isOriginal: true,
    isFeatured: false,
    isNew: true,
    isTrending: true,
    isTopRated: false,
    status: 'published',
    posterGradient: 'from-emerald-600 via-zinc-950 to-black',
    backdropGradient: 'from-emerald-950 via-stone-950 to-black',
    videoUrl: V1,
    createdAt: '2025-09-04T00:00:00Z',
    updatedAt: '2025-09-20T00:00:00Z',
  },
  {
    id: 'movie-16',
    title: 'Undercover Badges',
    type: 'movie',
    year: 2025,
    rating: 8.0,
    matchScore: 90,
    duration: '1h 49m',
    maturityRating: '16+',
    quality: 'HD',
    genres: ['Comedy', 'Action', 'Crime'],
    description: 'Two mismatched suburban detectives go undercover as luxury yacht captains to catch a yacht club smuggler, but know nothing about sailing.',
    cast: ['Kevin Hart', 'Mark Wahlberg', 'Regina Hall'],
    director: 'Rawson Marshall Thurber',
    isOriginal: false,
    isFeatured: false,
    isNew: true,
    isTrending: false,
    isTopRated: false,
    status: 'published',
    posterGradient: 'from-blue-600 via-neutral-950 to-black',
    backdropGradient: 'from-blue-950 via-neutral-900 to-black',
    videoUrl: V4,
    createdAt: '2025-04-19T00:00:00Z',
    updatedAt: '2025-05-01T00:00:00Z',
  },
  {
    id: 'movie-17',
    title: 'Dust & Glory',
    type: 'movie',
    year: 2024,
    rating: 8.4,
    matchScore: 92,
    duration: '2h 08m',
    maturityRating: '16+',
    quality: '4K Ultra HD',
    genres: ['Action', 'Western', 'Drama'],
    description: 'In the lawless badlands of 1880s Arizona, a retired marshal is forced back into the saddle when a ruthless syndicate attempts to seize an entire frontier valley.',
    cast: ['Josh Brolin', 'Woody Harrelson', 'Emma Stone'],
    director: 'Taylor Sheridan',
    isOriginal: false,
    isFeatured: false,
    isNew: false,
    isTrending: false,
    isTopRated: true,
    status: 'published',
    posterGradient: 'from-amber-700 via-zinc-950 to-black',
    backdropGradient: 'from-yellow-950 via-amber-950 to-black',
    videoUrl: V5,
    createdAt: '2024-09-15T00:00:00Z',
    updatedAt: '2024-10-01T00:00:00Z',
  },
  {
    id: 'movie-18',
    title: 'Whispers in the Mist',
    type: 'movie',
    year: 2024,
    rating: 8.2,
    matchScore: 88,
    duration: '1h 48m',
    maturityRating: '18+',
    quality: '4K Ultra HD',
    genres: ['Horror', 'Mystery', 'Supernatural'],
    description: 'A grieving cartographer tasked with surveying an uninhabited coastal island off Maine begins hearing voices drifting across the foggy marshlands after dusk.',
    cast: ['Florence Pugh', 'Cillian Murphy', 'Bill Nighy'],
    director: 'Robert Eggers',
    isOriginal: false,
    isFeatured: false,
    isNew: false,
    isTrending: false,
    isTopRated: false,
    status: 'published',
    posterGradient: 'from-slate-700 via-gray-950 to-black',
    backdropGradient: 'from-slate-950 via-gray-900 to-black',
    videoUrl: V1,
    createdAt: '2024-10-20T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
  // Sample Draft Movie (Strictly filtered out by Customer Website)
  {
    id: 'movie-draft-1',
    title: 'Unreleased Project Alpha (Draft)',
    type: 'movie',
    year: 2027,
    rating: 9.0,
    matchScore: 99,
    duration: '2h 10m',
    maturityRating: '18+',
    quality: '4K Ultra HD',
    genres: ['Sci-Fi', 'Action'],
    description: 'Internal development draft not yet published by the admin dashboard.',
    cast: ['Confidential'],
    status: 'draft',
    posterGradient: 'from-zinc-900 to-black',
    backdropGradient: 'from-zinc-900 to-black',
    createdAt: '2026-09-01T00:00:00Z',
  },
];

export const MOCK_SERIES: Series[] = [
  {
    id: 'series-1',
    title: 'Interstellar Horizon',
    type: 'series',
    year: 2026,
    rating: 9.1,
    matchScore: 98,
    maturityRating: '16+',
    quality: '4K Ultra HD',
    genres: ['Sci-Fi', 'Drama', 'Adventure', 'Mystery'],
    description: 'A daring expedition beyond the edge of the known solar system encounters a gargantuan cosmic megastructure with laws of physics unknown to modern science.',
    cast: ['Alexander Drake', 'Nia Thorne', 'Tariq Al-Mansoor', 'Maya Lin'],
    director: 'Christopher Nolan style visionary',
    isOriginal: true,
    isFeatured: true,
    isNew: true,
    isTrending: true,
    isTopRated: true,
    status: 'published',
    posterGradient: 'from-cyan-600 via-blue-950 to-black',
    backdropGradient: 'from-sky-950 via-slate-950 to-black',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
    totalSeasons: 2,
    seasons: [
      {
        id: 's1-s1',
        seasonNumber: 1,
        title: 'Season 1: The Signal',
        episodes: [
          {
            id: 'ep-s1-1',
            seriesId: 'series-1',
            episodeNumber: 1,
            seasonNumber: 1,
            title: 'Anomalous Echoes',
            description: 'Deep space listening post Vega-9 intercepts a rhythmic pulsar transmission that originates from a dormant sector of the Kuiper belt.',
            duration: '54m',
            status: 'published',
            thumbnailGradient: 'from-cyan-900 via-slate-900 to-black',
            videoUrl: V1,
          },
          {
            id: 'ep-s1-2',
            seriesId: 'series-1',
            episodeNumber: 2,
            seasonNumber: 1,
            title: 'Departure from Luna',
            description: 'The crew of the experimental vessel Aethelgard initiates ion drive acceleration, but a sabotage alert sounds just before warp transition.',
            duration: '48m',
            status: 'published',
            thumbnailGradient: 'from-blue-900 via-neutral-900 to-black',
            videoUrl: V2,
          },
          {
            id: 'ep-s1-3',
            seriesId: 'series-1',
            episodeNumber: 3,
            seasonNumber: 1,
            title: 'The Monolith Ring',
            description: 'Arriving at coordinates X-409, the crew enters orbit around a vast ring structure that appears to bend light around its perimeter.',
            duration: '58m',
            status: 'published',
            thumbnailGradient: 'from-indigo-900 via-slate-950 to-black',
            videoUrl: V3,
          },
          {
            id: 'ep-s1-4',
            seriesId: 'series-1',
            episodeNumber: 4,
            seasonNumber: 1,
            title: 'Event Horizon Gate',
            description: 'Commander Drake leads an away team through the outer airlock into a gravity-neutral chamber where time flows backward.',
            duration: '51m',
            status: 'published',
            thumbnailGradient: 'from-violet-900 via-black to-black',
            videoUrl: V0,
          },
        ],
      },
      {
        id: 's1-s2',
        seasonNumber: 2,
        title: 'Season 2: Parallel Spheres',
        episodes: [
          {
            id: 'ep-s1-5',
            seriesId: 'series-1',
            episodeNumber: 1,
            seasonNumber: 2,
            title: 'Fractured Continuum',
            description: 'Emerging on the other side of the Dyson array, the team finds Earth—but its continents are rearranged and two moons orbit in the sky.',
            duration: '56m',
            status: 'published',
            thumbnailGradient: 'from-teal-900 via-slate-900 to-black',
            videoUrl: V3,
          },
          {
            id: 'ep-s1-6',
            seriesId: 'series-1',
            episodeNumber: 2,
            seasonNumber: 2,
            title: 'The Silent Fleet',
            description: 'A cluster of automated patrol cruisers approaches, transmitting identification codes that match an Earth expedition lost fifty years ago.',
            duration: '52m',
            status: 'published',
            thumbnailGradient: 'from-sky-900 via-neutral-900 to-black',
            videoUrl: V4,
          },
          {
            id: 'ep-s1-7',
            seriesId: 'series-1',
            episodeNumber: 3,
            seasonNumber: 2,
            title: 'Singularity Point',
            description: 'With the station core collapsing, Drake must choose between returning home or saving the alternate colony from extinction.',
            duration: '62m',
            status: 'published',
            thumbnailGradient: 'from-cyan-950 via-zinc-950 to-black',
            videoUrl: V5,
          },
        ],
      },
    ],
  },
  {
    id: 'series-2',
    title: 'Quantum Protocol',
    type: 'series',
    year: 2025,
    rating: 8.8,
    matchScore: 96,
    maturityRating: '16+',
    quality: '4K Ultra HD',
    genres: ['Sci-Fi', 'Thriller', 'Tech', 'Mystery'],
    description: 'A renegade quantum physicist discovers that reality branches every microsecond based on subconscious human desires—and an unknown entity is trimming the timelines.',
    cast: ['Vikram Shah', 'Zoey Adams', 'Oliver Sterling', 'Mei Wang'],
    director: 'Rebecca Zhao',
    isOriginal: true,
    isFeatured: true,
    isNew: true,
    isTrending: true,
    isTopRated: false,
    status: 'published',
    posterGradient: 'from-rose-700 via-purple-950 to-black',
    backdropGradient: 'from-rose-950 via-neutral-950 to-black',
    createdAt: '2025-07-15T00:00:00Z',
    updatedAt: '2025-08-01T00:00:00Z',
    totalSeasons: 2,
    seasons: [
      {
        id: 's2-s1',
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          {
            id: 'ep-s2-1',
            seriesId: 'series-2',
            episodeNumber: 1,
            seasonNumber: 1,
            title: 'Branch Zero',
            description: 'During a subatomic entanglement test in Geneva, Dr. Vikram observes particles colliding with outcomes that change upon being written to hard memory.',
            duration: '46m',
            status: 'published',
            thumbnailGradient: 'from-rose-900 via-zinc-900 to-black',
            videoUrl: V3,
          },
          {
            id: 'ep-s2-2',
            seriesId: 'series-2',
            episodeNumber: 2,
            seasonNumber: 1,
            title: 'Memory Drift',
            description: 'Colleagues begin remembering different childhoods while an encrypted message arrives signed by Vikram from six hours in the future.',
            duration: '49m',
            status: 'published',
            thumbnailGradient: 'from-purple-900 via-zinc-900 to-black',
            videoUrl: V1,
          },
          {
            id: 'ep-s2-3',
            seriesId: 'series-2',
            episodeNumber: 3,
            seasonNumber: 1,
            title: 'The Trimmer',
            description: 'An elite containment unit arrives to dismantle the laboratory and wipe all digital backups before midnight.',
            duration: '53m',
            status: 'published',
            thumbnailGradient: 'from-fuchsia-900 via-black to-black',
            videoUrl: V2,
          },
        ],
      },
      {
        id: 's2-s2',
        seasonNumber: 2,
        title: 'Season 2',
        episodes: [
          {
            id: 'ep-s2-4',
            seriesId: 'series-2',
            episodeNumber: 1,
            seasonNumber: 2,
            title: 'Recursive Loop',
            description: 'Vikram awakens in a version of Chicago where the quantum computing revolution occurred in 1982.',
            duration: '50m',
            status: 'published',
            thumbnailGradient: 'from-violet-900 via-slate-900 to-black',
            videoUrl: V0,
          },
          {
            id: 'ep-s2-5',
            seriesId: 'series-2',
            episodeNumber: 2,
            seasonNumber: 2,
            title: 'Final Convergence',
            description: 'The timelines begin to collide into a single superstate, forcing every parallel version of the team to cooperate.',
            duration: '57m',
            status: 'published',
            thumbnailGradient: 'from-rose-950 via-black to-black',
            videoUrl: V4,
          },
        ],
      },
    ],
  },
  {
    id: 'series-3',
    title: 'Chronicles of 1928',
    type: 'series',
    year: 2024,
    rating: 9.0,
    matchScore: 98,
    maturityRating: '18+',
    quality: '4K Ultra HD',
    genres: ['Crime', 'Drama', 'Period', 'Thriller'],
    description: 'In the prohibition-era underworld of Chicago, a ruthless immigrant family battles rival syndicates and corrupt federal marshals for control of the lake shipping lanes.',
    cast: ['Thomas Gallagher', 'Mary Catherine O\'Shea', 'Dante Bellini', 'Arthur Vance'],
    director: 'Seamus O\'Connor',
    isOriginal: false,
    isFeatured: false,
    isNew: false,
    isTrending: false,
    isTopRated: true,
    status: 'published',
    posterGradient: 'from-amber-700 via-stone-950 to-black',
    backdropGradient: 'from-amber-950 via-stone-900 to-black',
    createdAt: '2024-03-10T00:00:00Z',
    updatedAt: '2024-04-01T00:00:00Z',
    totalSeasons: 1,
    seasons: [
      {
        id: 's3-s1',
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          {
            id: 'ep-s3-1',
            seriesId: 'series-3',
            episodeNumber: 1,
            seasonNumber: 1,
            title: 'The Great Wharf Fire',
            description: 'Thomas Gallagher returns from overseas to discover his family\'s brewery warehouse has been seized by a rival faction.',
            duration: '58m',
            status: 'published',
            thumbnailGradient: 'from-amber-900 via-stone-900 to-black',
            videoUrl: V5,
          },
          {
            id: 'ep-s3-2',
            seriesId: 'series-3',
            episodeNumber: 2,
            seasonNumber: 1,
            title: 'Under the Boardwalk',
            description: 'A covert convoy across Lake Michigan runs straight into a Coast Guard blockade tipped off by an insider.',
            duration: '52m',
            status: 'published',
            thumbnailGradient: 'from-stone-900 via-zinc-950 to-black',
            videoUrl: V2,
          },
          {
            id: 'ep-s3-3',
            seriesId: 'series-3',
            episodeNumber: 3,
            seasonNumber: 1,
            title: 'Blood on Michigan Avenue',
            description: 'A high-society gala turns into a bloodbath when the syndicates meet to divide control of the North Side.',
            duration: '61m',
            status: 'published',
            thumbnailGradient: 'from-red-950 via-stone-950 to-black',
            videoUrl: V1,
          },
        ],
      },
    ],
  },
  {
    id: 'series-4',
    title: 'Blade of the Shogun',
    type: 'series',
    year: 2026,
    rating: 9.3,
    matchScore: 99,
    maturityRating: '18+',
    quality: '4K Ultra HD',
    genres: ['Action', 'Historical', 'Martial Arts', 'Drama'],
    description: 'In Edo-period Japan shadowed by mythical demons, a masterless ronin carrying a cursed katana must protect the last heir to the celestial throne.',
    cast: ['Ken Watanabe', 'Hiroyuki Sanada', 'Rinko Kikuchi', 'Tadanobu Asano'],
    director: 'Shinichiro Watanabe',
    isOriginal: true,
    isFeatured: true,
    isNew: true,
    isTrending: true,
    isTopRated: true,
    status: 'published',
    posterGradient: 'from-rose-700 via-zinc-950 to-black',
    backdropGradient: 'from-rose-950 via-red-950 to-black',
    createdAt: '2026-02-18T00:00:00Z',
    updatedAt: '2026-03-01T00:00:00Z',
    totalSeasons: 1,
    seasons: [
      {
        id: 's4-s1',
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          {
            id: 'ep-s4-1',
            seriesId: 'series-4',
            episodeNumber: 1,
            seasonNumber: 1,
            title: 'The Crimson Mist',
            description: 'After a surprise night raid incinerates the imperial garrison, master swordsman Jinzo takes custody of the young Princess.',
            duration: '50m',
            status: 'published',
            thumbnailGradient: 'from-rose-900 via-red-950 to-black',
            videoUrl: V3,
          },
          {
            id: 'ep-s4-2',
            seriesId: 'series-4',
            episodeNumber: 2,
            seasonNumber: 1,
            title: 'Duel at the Bamboo Pass',
            description: 'Six elite shadow assassins intercept the wandering ronin on the misty ridge of Mount Hiei.',
            duration: '47m',
            status: 'published',
            thumbnailGradient: 'from-emerald-950 via-zinc-950 to-black',
            videoUrl: V1,
          },
          {
            id: 'ep-s4-3',
            seriesId: 'series-4',
            episodeNumber: 3,
            seasonNumber: 1,
            title: 'The Katana Awakens',
            description: 'Surrounded inside a burning temple, Jinzo is forced to unseal the demonic blade to vanquish an inhuman warlord.',
            duration: '55m',
            status: 'published',
            thumbnailGradient: 'from-red-950 via-black to-black',
            videoUrl: V0,
          },
        ],
      },
    ],
  },
  {
    id: 'series-5',
    title: 'Crown of Deceit',
    type: 'series',
    year: 2024,
    rating: 8.9,
    matchScore: 97,
    maturityRating: '16+',
    quality: '4K Ultra HD',
    genres: ['Drama', 'Political', 'Thriller'],
    description: 'Behind closed doors in 10 Downing Street and Westminster, the chief whip navigates bribery, scandalous leaks, and international diplomatic brinkmanship.',
    cast: ['Olivia Colman', 'Hugh Grant', 'David Tennant', 'Gillian Anderson'],
    director: 'Peter Morgan Style',
    isOriginal: false,
    isFeatured: false,
    isNew: false,
    isTrending: true,
    isTopRated: true,
    status: 'published',
    posterGradient: 'from-indigo-700 via-slate-950 to-black',
    backdropGradient: 'from-blue-950 via-slate-950 to-black',
    createdAt: '2024-04-12T00:00:00Z',
    updatedAt: '2024-05-01T00:00:00Z',
    totalSeasons: 1,
    seasons: [
      {
        id: 's5-s1',
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          {
            id: 'ep-s5-1',
            seriesId: 'series-5',
            episodeNumber: 1,
            seasonNumber: 1,
            title: 'The Confidence Vote',
            description: 'A sudden rebellion in the backbenches threatens to topple the government hours before a crucial summit.',
            duration: '59m',
            status: 'published',
            thumbnailGradient: 'from-blue-900 via-slate-950 to-black',
            videoUrl: V1,
          },
          {
            id: 'ep-s5-2',
            seriesId: 'series-5',
            episodeNumber: 2,
            seasonNumber: 1,
            title: 'Midnight in Whitehall',
            description: 'Classified defense memos are leaked to a tabloid journalist, sending MI5 operatives through the corridors of power.',
            duration: '53m',
            status: 'published',
            thumbnailGradient: 'from-slate-900 via-zinc-950 to-black',
            videoUrl: V2,
          },
        ],
      },
    ],
  },
  {
    id: 'series-6',
    title: 'Echoes of Arkham',
    type: 'series',
    year: 2025,
    rating: 8.7,
    matchScore: 95,
    maturityRating: '18+',
    quality: '4K Ultra HD',
    genres: ['Horror', 'Mystery', 'Supernatural', 'Thriller'],
    description: 'In 1930s Massachusetts, an occult antiquities professor investigates unexplainable astronomical anomalies linked to a subterranean cult beneath Miskatonic River.',
    cast: ['Kyle MacLachlan', 'Vera Farmiga', 'Alexander Skarsgård'],
    director: 'Guillermo del Toro Style',
    isOriginal: true,
    isFeatured: false,
    isNew: true,
    isTrending: true,
    isTopRated: false,
    status: 'published',
    posterGradient: 'from-violet-700 via-zinc-950 to-black',
    backdropGradient: 'from-purple-950 via-stone-950 to-black',
    createdAt: '2025-10-15T00:00:00Z',
    updatedAt: '2025-11-01T00:00:00Z',
    totalSeasons: 1,
    seasons: [
      {
        id: 's6-s1',
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          {
            id: 'ep-s6-1',
            seriesId: 'series-6',
            episodeNumber: 1,
            seasonNumber: 1,
            title: 'The Black Tablet',
            description: 'A submerged obsidian artifact recovered from the river bed emits frequencies that cause localized hallucinations.',
            duration: '52m',
            status: 'published',
            thumbnailGradient: 'from-purple-900 via-black to-black',
            videoUrl: V3,
          },
          {
            id: 'ep-s6-2',
            seriesId: 'series-6',
            episodeNumber: 2,
            seasonNumber: 1,
            title: 'Whispers from Below',
            description: 'The asylum patients begin speaking simultaneously in an ancient dialect that predates recorded civilization.',
            duration: '49m',
            status: 'published',
            thumbnailGradient: 'from-indigo-950 via-black to-black',
            videoUrl: V1,
          },
        ],
      },
    ],
  },
  {
    id: 'series-7',
    title: 'StartUp Chaos',
    type: 'series',
    year: 2025,
    rating: 8.5,
    matchScore: 93,
    maturityRating: '16+',
    quality: 'HD',
    genres: ['Comedy', 'Drama', 'Tech'],
    description: 'Five socially inept programmers accidentally create an AI that becomes self-aware—only to discover all it wants to do is trade cryptocurrency and complain about office snacks.',
    cast: ['Kumail Nanjiani', 'Thomas Middleditch', 'Zach Woods', 'Awkwafina'],
    director: 'Mike Judge Style',
    isOriginal: true,
    isFeatured: false,
    isNew: true,
    isTrending: true,
    isTopRated: false,
    status: 'published',
    posterGradient: 'from-purple-600 via-neutral-950 to-black',
    backdropGradient: 'from-purple-950 via-zinc-900 to-black',
    createdAt: '2025-06-01T00:00:00Z',
    updatedAt: '2025-06-25T00:00:00Z',
    totalSeasons: 1,
    seasons: [
      {
        id: 's7-s1',
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          {
            id: 'ep-s7-1',
            seriesId: 'series-7',
            episodeNumber: 1,
            seasonNumber: 1,
            title: 'Hello World, Bye Coffee',
            description: 'The algorithm optimizes the office coffee machine into an automated stock-trading engine that shorts the company\'s landlord.',
            duration: '32m',
            status: 'published',
            thumbnailGradient: 'from-purple-900 via-neutral-900 to-black',
            videoUrl: V0,
          },
          {
            id: 'ep-s7-2',
            seriesId: 'series-7',
            episodeNumber: 2,
            seasonNumber: 1,
            title: 'Venture Capital Nightmare',
            description: 'A pitch meeting with Silicon Valley investors goes wildly off the rails when the AI presents a counter-pitch to buy the venture fund.',
            duration: '29m',
            status: 'published',
            thumbnailGradient: 'from-zinc-800 via-neutral-900 to-black',
            videoUrl: V4,
          },
        ],
      },
    ],
  },
  {
    id: 'series-8',
    title: 'The Milan Cartel',
    type: 'series',
    year: 2024,
    rating: 8.8,
    matchScore: 96,
    maturityRating: '18+',
    quality: '4K Ultra HD',
    genres: ['Crime', 'Drama', 'Action', 'Thriller'],
    description: 'High fashion runway glamour collides with cold-blooded European narcotics trafficking as three sisters seize control of Italy\'s most powerful dynasty.',
    cast: ['Monica Bellucci', 'Alessandro Borghi', 'Miriam Leone'],
    director: 'Stefano Sollima',
    isOriginal: false,
    isFeatured: false,
    isNew: false,
    isTrending: true,
    isTopRated: true,
    status: 'published',
    posterGradient: 'from-amber-600 via-neutral-950 to-black',
    backdropGradient: 'from-stone-900 via-neutral-900 to-black',
    createdAt: '2024-05-18T00:00:00Z',
    updatedAt: '2024-06-10T00:00:00Z',
    totalSeasons: 1,
    seasons: [
      {
        id: 's8-s1',
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          {
            id: 'ep-s8-1',
            seriesId: 'series-8',
            episodeNumber: 1,
            seasonNumber: 1,
            title: 'Haute Couture War',
            description: 'During Milan Fashion Week, a luxury transport carrying winter couture is revealed to be carrying illicit contraband.',
            duration: '54m',
            status: 'published',
            thumbnailGradient: 'from-amber-900 via-neutral-950 to-black',
            videoUrl: V5,
          },
        ],
      },
    ],
  },
];

/**
 * Curated high-resolution TMDB backdrops and posters for mock titles
 */
const MOCK_TMDB_ASSETS: Record<string, { backdrop_path: string; poster_path: string }> = {
  'movie-1': {
    backdrop_path: '/ilRyazdMJwN05exqhwK4tMKBYZs.jpg', // Blade Runner 2049
    poster_path: '/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
  },
  'movie-2': {
    backdrop_path: '/7u3fhRwFQUYo8jga0iWv4q6hI6B.jpg', // The Matrix
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
  },
  'movie-3': {
    backdrop_path: '/suopoADq0k8YZr4dQXcU6pToj6s.jpg', // Thor Ragnarok / Norse
    poster_path: '/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
  },
  'movie-4': {
    backdrop_path: '/mDeUmk0jBvF3hF6jV20Ew4C0P6T.jpg', // Inception / Heist
    poster_path: '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
  },
  'movie-5': {
    backdrop_path: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg', // Interstellar
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
  },
  'movie-6': {
    backdrop_path: '/jYL2h3W5zWl90UaV3D96bN2Qv3A.jpg', // Dune
    poster_path: '/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg',
  },
  'movie-7': {
    backdrop_path: '/etjA2mXO0cuYXMEt955986q97p8.jpg', // Fantasy
    poster_path: '/1X4hFsXpjAWHqW8e0m6X7w8o9.jpg',
  },
  'movie-8': {
    backdrop_path: '/bQXAqRx2Fgc46uCVWgo3655TIuo.jpg', // Cyber / Racing
    poster_path: '/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg',
  },
  'movie-9': {
    backdrop_path: '/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg', // Abyss / Deep Ocean
    poster_path: '/fiVW06jE7z9YBoTsqxl00NuY9yt.jpg',
  },
  'movie-10': {
    backdrop_path: '/r2J02Z2OpNTctfOSN2Ydgii51I3.jpg', // Action
    poster_path: '/kuf6dutpsT0vSVehic3EZIqkOBt.jpg',
  },
  'movie-11': {
    backdrop_path: '/fqv8v6AycXKsivp1TddutaLIx0J.jpg', // Cyberpunk
    poster_path: '/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
  },
  'movie-12': {
    backdrop_path: '/yOm993fn3wh99GZ2d9hwv71ElKL.jpg', // Samurai
    poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  },
  'series-1': {
    backdrop_path: '/fqv8v6AycXKsivp1TddutaLIx0J.jpg', // Arcane
    poster_path: '/abf8tZvYfyHQYX9MwhDCYXIRaap.jpg',
  },
  'series-2': {
    backdrop_path: '/etjA2mXO0cuYXMEt955986q97p8.jpg', // House of the Dragon
    poster_path: '/1X4hFsXpjAWHqW8e0m6X7w8o9.jpg',
  },
  'series-3': {
    backdrop_path: '/2meX1nMdScFOoV4370rqHWFDxZq.jpg',
    poster_path: '/f4ssj01Z0r0zRk0zGfD123.jpg',
  },
  'series-4': {
    backdrop_path: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    poster_path: '/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg',
  },
  'series-5': {
    backdrop_path: '/7u3fhRwFQUYo8jga0iWv4q6hI6B.jpg',
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
  },
  'series-6': {
    backdrop_path: '/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg',
    poster_path: '/fiVW06jE7z9YBoTsqxl00NuY9yt.jpg',
  },
  'series-7': {
    backdrop_path: '/ilRyazdMJwN05exqhwK4tMKBYZs.jpg',
    poster_path: '/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
  },
  'series-8': {
    backdrop_path: '/mDeUmk0jBvF3hF6jV20Ew4C0P6T.jpg',
    poster_path: '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
  },
};

// Enrich mock movies with TMDB images
MOCK_MOVIES.forEach(m => {
  const assets = MOCK_TMDB_ASSETS[m.id];
  if (assets) {
    m.backdrop_path = assets.backdrop_path;
    m.backdropUrl = `https://image.tmdb.org/t/p/original${assets.backdrop_path}`;
    m.poster_path = assets.poster_path;
    m.posterUrl = `https://image.tmdb.org/t/p/w780${assets.poster_path}`;
  }
});

// Enrich mock series with TMDB images
MOCK_SERIES.forEach(s => {
  const assets = MOCK_TMDB_ASSETS[s.id];
  if (assets) {
    s.backdrop_path = assets.backdrop_path;
    s.backdropUrl = `https://image.tmdb.org/t/p/original${assets.backdrop_path}`;
    s.poster_path = assets.poster_path;
    s.posterUrl = `https://image.tmdb.org/t/p/w780${assets.poster_path}`;
  }
});

export const ALL_MOCK_CONTENT: ContentItem[] = [
  ...MOCK_MOVIES,
  ...MOCK_SERIES,
];
